"""
PDF evidence report generator using fpdf2.

Creates a court-ready PDF document with violation details,
annotated images, and metadata.
"""

import json
import logging
import os
import zipfile
from datetime import datetime

from fpdf import FPDF

from backend.app.core.config import settings

logger = logging.getLogger(__name__)


class ViolationPDFReport(FPDF):
    """Custom PDF class for violation evidence reports."""

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "Traffic Violation Evidence Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 8)
        self.cell(0, 5, f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Confidential - For Official Use Only", align="C")


def generate_pdf_report(
    violation_id: str,
    violation_data: dict,
    thumbnail_path: str | None = None,
) -> str:
    """
    Generate a PDF evidence report for a violation.

    Args:
        violation_id: unique violation ID
        violation_data: dict with violation details
        thumbnail_path: optional path to annotated thumbnail image

    Returns:
        Path to the generated PDF file.
    """
    pdf = ViolationPDFReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Violation ID
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, f"Violation ID: {violation_id}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Details section
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 7, "Violation Details", new_x="LMARGIN", new_y="NEXT")
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    details = [
        ("Type", _format_violation_type(violation_data.get("violation_type", ""))),
        ("Camera ID", violation_data.get("camera_id", "N/A")),
        ("License Plate", violation_data.get("license_plate", "Not detected")),
        ("Confidence", f"{float(violation_data.get('confidence', 0)) * 100:.1f}%"),
        ("Detected At", violation_data.get("detected_at", datetime.utcnow().isoformat())),
        ("Details", violation_data.get("details", "")),
    ]

    pdf.set_font("Helvetica", "", 10)
    for label, value in details:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(45, 7, f"{label}:")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    # Thumbnail image
    if thumbnail_path and os.path.exists(thumbnail_path):
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, "Evidence Image", new_x="LMARGIN", new_y="NEXT")
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)

        try:
            # Scale image to fit page width
            pdf.image(thumbnail_path, x=10, w=190)
            pdf.ln(5)
        except Exception as e:
            logger.warning(f"Failed to embed thumbnail in PDF: {e}")
            pdf.cell(0, 7, "[Image not available]", new_x="LMARGIN", new_y="NEXT")

    # Metadata section
    bbox = violation_data.get("bbox")
    if bbox:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, "Detection Metadata", new_x="LMARGIN", new_y="NEXT")
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("Courier", "", 9)
        pdf.cell(0, 6, f"Bounding Box: {bbox}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 6, f"Frame ID: {violation_data.get('frame_id', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 6, f"Tracker ID: {violation_data.get('tracker_id', 'N/A')}", new_x="LMARGIN", new_y="NEXT")

    # Disclaimer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(
        0, 4,
        "This report was auto-generated by the Smart Traffic Violation Detection System. "
        "All detection results should be reviewed by authorized personnel before enforcement action. "
        "Evidence integrity is maintained through system audit logs."
    )

    # Save PDF
    output_path = os.path.join(settings.EVIDENCE_DIR, f"{violation_id}.pdf")
    os.makedirs(settings.EVIDENCE_DIR, exist_ok=True)
    pdf.output(output_path)
    logger.info(f"PDF report generated: {output_path}")
    return output_path


def generate_evidence_bundle(
    violation_id: str,
    violation_data: dict,
    clip_path: str | None = None,
    thumbnail_path: str | None = None,
) -> str:
    """
    Generate a ZIP evidence bundle containing:
    - PDF report
    - Video clip (if available)
    - Thumbnail image (if available)
    - JSON metadata

    Returns:
        Path to the generated ZIP file.
    """
    # Generate PDF first
    pdf_path = generate_pdf_report(violation_id, violation_data, thumbnail_path)

    # Create ZIP
    zip_filename = f"{violation_id}_evidence.zip"
    zip_path = os.path.join(settings.EVIDENCE_DIR, zip_filename)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        # Add PDF
        zf.write(pdf_path, f"report_{violation_id}.pdf")

        # Add clip if available
        if clip_path and os.path.exists(clip_path):
            zf.write(clip_path, f"clip_{violation_id}.mp4")

        # Add thumbnail if available
        if thumbnail_path and os.path.exists(thumbnail_path):
            zf.write(thumbnail_path, f"thumbnail_{violation_id}.jpg")

        # Add JSON metadata
        metadata = {
            "violation_id": violation_id,
            "generated_at": datetime.utcnow().isoformat(),
            "violation": violation_data,
        }
        zf.writestr(
            f"metadata_{violation_id}.json",
            json.dumps(metadata, indent=2, default=str),
        )

    logger.info(f"Evidence bundle generated: {zip_path}")
    return zip_path


def _format_violation_type(vtype: str) -> str:
    """Format violation type for display."""
    labels = {
        "helmet_violation": "No Helmet Violation",
        "signal_jump": "Signal Jump Violation",
        "wrong_way": "Wrong Way Driving",
        "speeding": "Speeding",
        "no_seatbelt": "No Seatbelt",
        "illegal_parking": "Illegal Parking",
    }
    if hasattr(vtype, "value"):
        vtype = vtype.value
    return labels.get(str(vtype), str(vtype).replace("_", " ").title())
